apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edgesphere-monitor
  namespace: edgesphere
spec:
  selector:
    matchLabels:
      version: v1
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
